-- SellerOS AI
-- Initial Supabase database schema
-- Reconstructed from the live production schema on 2026-09-03.

create extension if not exists pgcrypto;

-- =========================================================
-- AI IMAGE USAGE
-- =========================================================

create table public.ai_image_usage (
  id bigint generated by default as identity not null,
  etsy_user_id text not null,
  billing_month text not null,
  generation_count integer not null default 0,
  monthly_limit integer not null default 5,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint ai_image_usage_pkey
    primary key (id),

  constraint ai_image_usage_user_month_unique
    unique (etsy_user_id, billing_month),

  constraint ai_image_usage_generation_count_check
    check (generation_count >= 0),

  constraint ai_image_usage_monthly_limit_check
    check (monthly_limit >= 0)
);

-- =========================================================
-- ETSY CONNECTIONS
-- =========================================================

create table public.etsy_connections (
  etsy_user_id text not null,
  access_token text not null,
  refresh_token text not null,
  access_token_expires_at timestamp with time zone not null,
  scopes text[] not null default '{}'::text[],
  connection_status text not null default 'active'::text,
  last_refreshed_at timestamp with time zone,
  last_sync_at timestamp with time zone,
  last_error text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  user_id uuid,

  constraint etsy_connections_pkey
    primary key (etsy_user_id),

  constraint etsy_connections_user_id_fkey
    foreign key (user_id)
    references auth.users(id)
    on delete cascade,

  constraint etsy_connections_connection_status_check
    check (
      connection_status = any (
        array[
          'active'::text,
          'expired'::text,
          'revoked'::text
        ]
      )
    )
);

-- =========================================================
-- LISTING PROJECTS
-- =========================================================

create table public.listing_projects (
  id uuid not null default gen_random_uuid(),
  etsy_user_id text not null,
  status text not null default 'draft'::text,
  product_name text not null,
  product_description text not null,
  product_type text,
  source_materials text,
  primary_color text,
  secondary_color text,
  dimensions text,
  price numeric,
  quantity integer not null default 1,
  occasion text,
  personalization text,
  production_time text,
  generated_title text,
  generated_description text,
  generated_tags jsonb not null default '[]'::jsonb,
  generated_materials jsonb not null default '[]'::jsonb,
  generated_highlights jsonb not null default '[]'::jsonb,
  image_plan jsonb not null default '[]'::jsonb,
  etsy_listing_id bigint,
  etsy_listing_url text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  expires_at timestamp with time zone not null
    default (now() + '5 days'::interval),

  constraint listing_projects_pkey
    primary key (id),

  constraint listing_projects_quantity_check
    check (quantity >= 1),

  constraint listing_projects_status_check
    check (
      status = any (
        array[
          'draft'::text,
          'generating'::text,
          'ready'::text,
          'exporting'::text,
          'exported'::text,
          'failed'::text
        ]
      )
    )
);

-- =========================================================
-- LISTING PROJECT IMAGES
-- =========================================================

create table public.listing_project_images (
  id uuid not null default gen_random_uuid(),
  project_id uuid not null,
  etsy_user_id text not null,
  image_kind text not null,
  image_rank integer not null default 1,
  storage_path text,
  mime_type text,
  original_filename text,
  concept_title text,
  concept_description text,
  generation_instructions text,
  prompt_used text,
  alt_text text,
  generation_status text not null default 'pending'::text,
  error_message text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint listing_project_images_pkey
    primary key (id),

  constraint listing_project_images_project_id_fkey
    foreign key (project_id)
    references public.listing_projects(id)
    on delete cascade,

  constraint listing_project_images_project_rank_unique
    unique (project_id, image_kind, image_rank),

  constraint listing_project_images_image_rank_check
    check (image_rank >= 1),

  constraint listing_project_images_generation_status_check
    check (
      generation_status = any (
        array[
          'pending'::text,
          'generating'::text,
          'complete'::text,
          'failed'::text
        ]
      )
    ),

  constraint listing_project_images_image_kind_check
    check (
      image_kind = any (
        array[
          'source'::text,
          'studio'::text,
          'lifestyle'::text,
          'detail'::text,
          'scale'::text,
          'gift'::text,
          'seasonal'::text
        ]
      )
    )
);

-- =========================================================
-- ETSY EXPORT HISTORY
-- =========================================================

create table public.etsy_export_history (
  id uuid not null default gen_random_uuid(),
  etsy_user_id text not null,
  source_project_id uuid,
  etsy_shop_id bigint not null,
  etsy_shop_name text,
  etsy_listing_id bigint not null,
  listing_title text not null,
  listing_url text,
  uploaded_image_count integer not null default 0,
  etsy_state text not null default 'draft'::text,
  project_cleanup_completed boolean not null default false,
  project_cleanup_error text,
  exported_at timestamp with time zone not null default now(),
  last_etsy_synced_at timestamp with time zone,

  constraint etsy_export_history_pkey
    primary key (id),

  constraint etsy_export_history_user_listing_unique
    unique (etsy_user_id, etsy_listing_id),

  constraint etsy_export_history_uploaded_image_count_check
    check (uploaded_image_count >= 0)
);

-- =========================================================
-- ETSY LISTING UPDATE HISTORY
-- =========================================================

create table public.etsy_listing_update_history (
  id uuid not null default gen_random_uuid(),
  etsy_user_id text not null,
  etsy_shop_id bigint not null,
  etsy_shop_name text,
  etsy_listing_id bigint not null,
  listing_title text,
  updated_title boolean not null default false,
  updated_description boolean not null default false,
  updated_tags boolean not null default false,
  previous_title text,
  new_title text,
  previous_description text,
  new_description text,
  previous_tags text[] not null default '{}'::text[],
  new_tags text[] not null default '{}'::text[],
  update_status text not null default 'success'::text,
  error_message text,
  updated_at timestamp with time zone not null default now(),

  constraint etsy_listing_update_history_pkey
    primary key (id),

  constraint etsy_listing_update_history_update_status_check
    check (
      update_status = any (
        array[
          'success'::text,
          'failed'::text
        ]
      )
    )
);

-- =========================================================
-- ETSY OPTIMIZATION SNAPSHOTS
-- =========================================================

create table public.etsy_optimization_snapshots (
  id uuid not null default gen_random_uuid(),
  etsy_user_id text not null,
  update_history_id uuid not null,
  etsy_shop_id bigint not null,
  etsy_listing_id bigint not null,
  listing_title text,
  snapshot_stage text not null,
  listing_state text,
  favorite_count integer not null default 0,
  transaction_count integer not null default 0,
  units_sold integer not null default 0,
  revenue_amount numeric not null default 0,
  revenue_currency text,
  snapshot_error text,
  captured_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),

  constraint etsy_optimization_snapshots_pkey
    primary key (id),

  constraint etsy_optimization_snapshots_update_history_id_fkey
    foreign key (update_history_id)
    references public.etsy_listing_update_history(id)
    on delete cascade,

  constraint etsy_optimization_snapshots_favorite_count_check
    check (favorite_count >= 0),

  constraint etsy_optimization_snapshots_transaction_count_check
    check (transaction_count >= 0),

  constraint etsy_optimization_snapshots_units_sold_check
    check (units_sold >= 0),

  constraint etsy_optimization_snapshots_revenue_amount_check
    check (revenue_amount >= 0),

  constraint etsy_optimization_snapshots_snapshot_stage_check
    check (
      snapshot_stage = any (
        array[
          'baseline'::text,
          'day_7'::text,
          'day_14'::text,
          'day_30'::text,
          'manual'::text
        ]
      )
    )
);

-- =========================================================
-- SELLEROS SUBSCRIPTIONS
-- =========================================================

create table public.selleros_subscriptions (
  user_id uuid not null,
  stripe_customer_id text,
  stripe_subscription_id text,
  stripe_price_id text,
  plan_key text not null default 'early_access'::text,
  subscription_status text not null default 'early_access'::text,
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  cancel_at_period_end boolean not null default false,
  canceled_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  cancel_at timestamp with time zone,
  last_stripe_event_created bigint,
  last_stripe_event_id text,

  constraint selleros_subscriptions_pkey
    primary key (user_id),

  constraint selleros_subscriptions_user_id_fkey
    foreign key (user_id)
    references auth.users(id)
    on delete cascade,

  constraint selleros_subscriptions_stripe_customer_id_key
    unique (stripe_customer_id),

  constraint selleros_subscriptions_stripe_subscription_id_key
    unique (stripe_subscription_id)
);

-- =========================================================
-- FUNCTIONS
-- =========================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path to 'public'
as $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

create or replace function public.refresh_listing_project_expiration()
returns trigger
language plpgsql
as $function$
begin
  new.expires_at =
    now() + interval '5 days';

  return new;
end;
$function$;

-- =========================================================
-- TRIGGERS
-- =========================================================

create trigger set_listing_project_images_updated_at
before update on public.listing_project_images
for each row
execute function public.set_updated_at();

create trigger refresh_listing_project_expiration_trigger
before update on public.listing_projects
for each row
execute function public.refresh_listing_project_expiration();

create trigger set_listing_projects_updated_at
before update on public.listing_projects
for each row
execute function public.set_updated_at();

-- =========================================================
-- INDEXES
-- =========================================================

create index ai_image_usage_etsy_user_id_idx
  on public.ai_image_usage using btree (etsy_user_id);

create index etsy_connections_status_idx
  on public.etsy_connections using btree (connection_status);

create unique index etsy_connections_user_id_unique
  on public.etsy_connections using btree (user_id)
  where user_id is not null;

create index etsy_export_history_listing_id_idx
  on public.etsy_export_history using btree (etsy_listing_id);

create index etsy_export_history_user_exported_at_idx
  on public.etsy_export_history using btree (
    etsy_user_id,
    exported_at desc
  );

create index etsy_export_history_user_synced_at_idx
  on public.etsy_export_history using btree (
    etsy_user_id,
    last_etsy_synced_at desc
  );

create index etsy_listing_update_history_listing_index
  on public.etsy_listing_update_history using btree (
    etsy_listing_id,
    updated_at desc
  );

create index etsy_listing_update_history_user_index
  on public.etsy_listing_update_history using btree (
    etsy_user_id,
    updated_at desc
  );

create index etsy_optimization_snapshots_listing_index
  on public.etsy_optimization_snapshots using btree (
    etsy_listing_id,
    captured_at desc
  );

create unique index etsy_optimization_snapshots_stage_unique
  on public.etsy_optimization_snapshots using btree (
    update_history_id,
    snapshot_stage
  );

create index etsy_optimization_snapshots_user_index
  on public.etsy_optimization_snapshots using btree (
    etsy_user_id,
    captured_at desc
  );

create index listing_project_images_etsy_user_id_idx
  on public.listing_project_images using btree (etsy_user_id);

create index listing_project_images_project_id_idx
  on public.listing_project_images using btree (project_id);

create index listing_projects_created_at_idx
  on public.listing_projects using btree (created_at desc);

create index listing_projects_etsy_user_id_idx
  on public.listing_projects using btree (etsy_user_id);

create index listing_projects_expires_at_idx
  on public.listing_projects using btree (expires_at);

create index listing_projects_status_idx
  on public.listing_projects using btree (status);

create index selleros_subscriptions_customer_index
  on public.selleros_subscriptions using btree (stripe_customer_id);

create index selleros_subscriptions_status_index
  on public.selleros_subscriptions using btree (subscription_status);

-- =========================================================
-- ROW LEVEL SECURITY
-- =========================================================

alter table public.ai_image_usage
  enable row level security;

alter table public.etsy_connections
  enable row level security;

alter table public.etsy_export_history
  enable row level security;

alter table public.etsy_listing_update_history
  enable row level security;

alter table public.etsy_optimization_snapshots
  enable row level security;

alter table public.listing_project_images
  enable row level security;

alter table public.listing_projects
  enable row level security;

alter table public.selleros_subscriptions
  enable row level security;

-- =========================================================
-- STORAGE
-- =========================================================

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'listing-project-images',
  'listing-project-images',
  false,
  10485760,
  array[
    'image/png',
    'image/jpeg',
    'image/webp'
  ]::text[]
);